# ./config/datadog/postgres.d/conf.yaml
init_config:

instances:
  - dbm: true
    host: postgres
    port: 5432
    username: datadog
    password: datadog
    dbname: postgres
    tags:
      - env:development
      - service:postgres 